name: parameter-space
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - scipy
  - ipywidgets
  - jupyter
  - pandas
  - pip
  - pip:
      - parameter-space==0.1.0
      - pde-rk==0.1.0
